# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stt_worker_pb2 as stt__worker__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stt_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class STTWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeFile = channel.unary_unary(
                '/macaw.stt.STTWorker/TranscribeFile',
                request_serializer=stt__worker__pb2.TranscribeFileRequest.SerializeToString,
                response_deserializer=stt__worker__pb2.TranscribeFileResponse.FromString,
                _registered_method=True)
        self.TranscribeStream = channel.stream_stream(
                '/macaw.stt.STTWorker/TranscribeStream',
                request_serializer=stt__worker__pb2.AudioFrame.SerializeToString,
                response_deserializer=stt__worker__pb2.TranscriptEvent.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/macaw.stt.STTWorker/Cancel',
                request_serializer=stt__worker__pb2.CancelRequest.SerializeToString,
                response_deserializer=stt__worker__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/macaw.stt.STTWorker/Health',
                request_serializer=stt__worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=stt__worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class STTWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeFile(self, request, context):
        """Batch transcription (full file)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeStream(self, request_iterator, context):
        """Streaming transcription (bidirectional)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Request/session cancellation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeFile,
                    request_deserializer=stt__worker__pb2.TranscribeFileRequest.FromString,
                    response_serializer=stt__worker__pb2.TranscribeFileResponse.SerializeToString,
            ),
            'TranscribeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TranscribeStream,
                    request_deserializer=stt__worker__pb2.AudioFrame.FromString,
                    response_serializer=stt__worker__pb2.TranscriptEvent.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=stt__worker__pb2.CancelRequest.FromString,
                    response_serializer=stt__worker__pb2.CancelResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=stt__worker__pb2.HealthRequest.FromString,
                    response_serializer=stt__worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'macaw.stt.STTWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('macaw.stt.STTWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class STTWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macaw.stt.STTWorker/TranscribeFile',
            stt__worker__pb2.TranscribeFileRequest.SerializeToString,
            stt__worker__pb2.TranscribeFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/macaw.stt.STTWorker/TranscribeStream',
            stt__worker__pb2.AudioFrame.SerializeToString,
            stt__worker__pb2.TranscriptEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macaw.stt.STTWorker/Cancel',
            stt__worker__pb2.CancelRequest.SerializeToString,
            stt__worker__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macaw.stt.STTWorker/Health',
            stt__worker__pb2.HealthRequest.SerializeToString,
            stt__worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
