# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tts_worker.proto\x12\tmacaw.tts\"\xb4\x01\n\x11SynthesizeRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05voice\x18\x03 \x01(\t\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\x10\n\x08language\x18\x06 \x01(\t\x12\x11\n\tref_audio\x18\x07 \x01(\x0c\x12\x10\n\x08ref_text\x18\x08 \x01(\t\x12\x13\n\x0binstruction\x18\t \x01(\t\"H\n\x0fSynthesizeChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"\x13\n\x11ListVoicesRequest\"R\n\x0eVoiceInfoProto\x12\x10\n\x08voice_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\"?\n\x12ListVoicesResponse\x12)\n\x06voices\x18\x01 \x03(\x0b\x32\x19.macaw.tts.VoiceInfoProto\"\x0f\n\rHealthRequest\"\xb0\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x03 \x01(\t\x12\x39\n\x08metadata\x18\x04 \x03(\x0b\x32\'.macaw.tts.HealthResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xdf\x01\n\tTTSWorker\x12H\n\nSynthesize\x12\x1c.macaw.tts.SynthesizeRequest\x1a\x1a.macaw.tts.SynthesizeChunk0\x01\x12I\n\nListVoices\x12\x1c.macaw.tts.ListVoicesRequest\x1a\x1d.macaw.tts.ListVoicesResponse\x12=\n\x06Health\x12\x18.macaw.tts.HealthRequest\x1a\x19.macaw.tts.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_HEALTHRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SYNTHESIZEREQUEST']._serialized_start=32
  _globals['_SYNTHESIZEREQUEST']._serialized_end=212
  _globals['_SYNTHESIZECHUNK']._serialized_start=214
  _globals['_SYNTHESIZECHUNK']._serialized_end=286
  _globals['_LISTVOICESREQUEST']._serialized_start=288
  _globals['_LISTVOICESREQUEST']._serialized_end=307
  _globals['_VOICEINFOPROTO']._serialized_start=309
  _globals['_VOICEINFOPROTO']._serialized_end=391
  _globals['_LISTVOICESRESPONSE']._serialized_start=393
  _globals['_LISTVOICESRESPONSE']._serialized_end=456
  _globals['_HEALTHREQUEST']._serialized_start=458
  _globals['_HEALTHREQUEST']._serialized_end=473
  _globals['_HEALTHRESPONSE']._serialized_start=476
  _globals['_HEALTHRESPONSE']._serialized_end=652
  _globals['_HEALTHRESPONSE_METADATAENTRY']._serialized_start=605
  _globals['_HEALTHRESPONSE_METADATAENTRY']._serialized_end=652
  _globals['_TTSWORKER']._serialized_start=655
  _globals['_TTSWORKER']._serialized_end=878
# @@protoc_insertion_point(module_scope)
