# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vc_worker_pb2 as vc__worker__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vc_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VCWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoiceChange = channel.unary_stream(
                '/macaw.vc.VCWorker/VoiceChange',
                request_serializer=vc__worker__pb2.VoiceChangeRequest.SerializeToString,
                response_deserializer=vc__worker__pb2.VoiceChangeChunk.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/macaw.vc.VCWorker/Health',
                request_serializer=vc__worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=vc__worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class VCWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VoiceChange(self, request, context):
        """Voice conversion (server-streaming: source audio in, converted audio chunks out)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VCWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoiceChange': grpc.unary_stream_rpc_method_handler(
                    servicer.VoiceChange,
                    request_deserializer=vc__worker__pb2.VoiceChangeRequest.FromString,
                    response_serializer=vc__worker__pb2.VoiceChangeChunk.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=vc__worker__pb2.HealthRequest.FromString,
                    response_serializer=vc__worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'macaw.vc.VCWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('macaw.vc.VCWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VCWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VoiceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/macaw.vc.VCWorker/VoiceChange',
            vc__worker__pb2.VoiceChangeRequest.SerializeToString,
            vc__worker__pb2.VoiceChangeChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macaw.vc.VCWorker/Health',
            vc__worker__pb2.HealthRequest.SerializeToString,
            vc__worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
