# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vc_worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vc_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvc_worker.proto\x12\x08macaw.vc\"\xa4\x01\n\x12VoiceChangeRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0csource_audio\x18\x02 \x01(\x0c\x12\r\n\x05voice\x18\x03 \x01(\t\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\x11\n\tref_audio\x18\x05 \x01(\x0c\x12\x10\n\x08ref_text\x18\x06 \x01(\t\x12\x1b\n\x13voice_settings_json\x18\x07 \x01(\t\"I\n\x10VoiceChangeChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"\x0f\n\rHealthRequest\"D\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x03 \x01(\t2\x92\x01\n\x08VCWorker\x12I\n\x0bVoiceChange\x12\x1c.macaw.vc.VoiceChangeRequest\x1a\x1a.macaw.vc.VoiceChangeChunk0\x01\x12;\n\x06Health\x12\x17.macaw.vc.HealthRequest\x1a\x18.macaw.vc.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vc_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICECHANGEREQUEST']._serialized_start=30
  _globals['_VOICECHANGEREQUEST']._serialized_end=194
  _globals['_VOICECHANGECHUNK']._serialized_start=196
  _globals['_VOICECHANGECHUNK']._serialized_end=269
  _globals['_HEALTHREQUEST']._serialized_start=271
  _globals['_HEALTHREQUEST']._serialized_end=286
  _globals['_HEALTHRESPONSE']._serialized_start=288
  _globals['_HEALTHRESPONSE']._serialized_end=356
  _globals['_VCWORKER']._serialized_start=359
  _globals['_VCWORKER']._serialized_end=505
# @@protoc_insertion_point(module_scope)
